### ISSUE TITLE
Issue with icon spacing in multiselect values

### ISSUE THREAD

**Issue by Godisemo** [tcbegley/dash-bootstrap-css#11]
There seems to be an issue in all themes with spacing of the x-icon in the multiselect values.
I'm currently using the following versions:
* dash==1.11.0
* dash-bootstrap-components==0.9.2
* dash-core-components==1.9.1
* dash-html-components==1.0.3

<img width="814" alt="Screenshot 2020-04-12 at 15 32 02" src="https://user-images.githubusercontent.com/847898/79070193-68b7ac00-7cd4-11ea-863c-51375bf345ca.png">

**Comment by Godisemo** [comment]
I'm not sure it is a perfect fix, but adding
```css
.dash-bootstrap .Select--multi .Select-value-icon,
.dash-bootstrap .Select--multi .Select-value-label {
    vertical-align: top;
}
```
seems to do it for me.
